# Generated by Django 2.1.3 on 2019-01-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dj_disc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('aid', models.IntegerField()),
                ('content', models.CharField(max_length=2000)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dj_disc',
                'ordering': ['-c_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Fenle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fl_name', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'dj_fenle',
            },
        ),
    ]
