# Generated by Django 2.1.3 on 2019-01-02 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj_disc',
            name='fenle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disc.Fenle'),
        ),
    ]
