# Generated by Django 2.1.3 on 2019-01-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disc', '0002_dj_disc_fenle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dj_tag',
            },
        ),
        migrations.AddField(
            model_name='dj_disc',
            name='tag',
            field=models.ManyToManyField(to='disc.Tag'),
        ),
    ]
