# Generated by Django 2.1.3 on 2019-01-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disc', '0003_auto_20190109_2139'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
    ]
