# Generated by Django 2.1.3 on 2019-01-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disc', '0004_auto_20190109_2153'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='dj_tag',
        ),
    ]
