"""
Django settings for pyweb project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# 项目当前所在路径
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wzgk()qjwl98cag#k_x9f&9l03h!o*x!423y7-&_8w@*zm5f6%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 外网或局域网访问域名
ALLOWED_HOSTS = []


# Application definition
# app配置项
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'frot',
    'book',
    'cms',
    'disc',
    'user',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pyweb.urls'
# 模板配置
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 模板目录
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        # app模板文件，默认为True开启，如果上面查找不到会进入app中的templates文件夹查找
        # 如果要使用app模板就必须在配置项INSTALLED_APPS中添加这个app
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # 由于模板中的static不是内置标签，所以每次使用都要在模板中load，比较麻烦
            # 添加下面这个配置项可以吧不是内置标签的标签设置成为内置标签
            'builtins':['django.templatetags.static'],
        },
    },
]

WSGI_APPLICATION = 'pyweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
# 数据库连接配置
DATABASES = {
    'default': {
        # 数据库引擎
        'ENGINE': 'django.db.backends.mysql',
        # 数据库名称
        'NAME': 'dj_db',
        # 数据库名
        'USER':'root',
        # 数据库密码
        'PASSWORD':'123456',
        # 数据库主机地址
        'HOST':'127.0.0.1',
        # 数据库端口号
        'PORT':'3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
# 对应django封装的timezone时区的设置
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True
# 如果这个设置为False 那么会获取到的当前时间就是一个navie类型的时间
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
# 请求静态文件的url配置
STATIC_URL = '/static/'

# 这个配置可以定义app以外的静态文件夹，定义了这个方法后如果在app找不到静态资源会自动去app以外的路径寻找静态资源
STATICFILES_DIRS=[
    os.path.join(BASE_DIR, 'static')
]
